name: Node Directory Update
on:
  issues:
    types: [opened, edited, closed]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        run: python tools/node-directory/generate.py
      - name: Commit Change
        run: |
          git config --global user.name 'NodeBot'
          git add nodes.json
          git commit -m "Automated Node Update" || echo "No changes to commit"
          git push